# Generated by Django 4.1.7 on 2023-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('VK', 'VK'), ('Telegram', 'Telegram')], default=('WhatsApp', 'WhatsApp'), max_length=50)),
                ('url', models.URLField()),
                ('media', models.ImageField(upload_to='main/images/social_clubs/')),
            ],
            options={
                'verbose_name': 'соц. сеть',
                'verbose_name_plural': 'Соц. сети',
            },
        ),
    ]
