# Generated by Django 4.1.7 on 2023-03-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Имя')),
                ('social_club', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('VK', 'VK'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('OK', 'OK'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], default=('WhatsApp', 'WhatsApp'), max_length=50, verbose_name='Соц. сеть')),
                ('social_club_url', models.URLField(verbose_name='Ссылка на соцю сеть')),
                ('media', models.ImageField(upload_to='main/images/moderators', verbose_name='Фотография модератора')),
            ],
            options={
                'verbose_name': 'модератора',
                'verbose_name_plural': 'Модераторы',
            },
        ),
        migrations.RemoveField(
            model_name='socialclub',
            name='media',
        ),
        migrations.AlterField(
            model_name='socialclub',
            name='title',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('VK', 'VK'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('OK', 'OK'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], default=('WhatsApp', 'WhatsApp'), max_length=50),
        ),
    ]
