# Generated by Django 4.1.7 on 2023-03-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_formbid_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbid',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formbid',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
