# Generated by Django 4.1.7 on 2023-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_formbid_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео с YouTube')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Дата и время добавления (МСК)')),
                ('status', models.BooleanField(verbose_name='Отображать')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
