# Generated by Django 4.1.7 on 2023-03-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=100, verbose_name='Содержание')),
                ('visible', models.BooleanField(verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'информацию',
                'verbose_name_plural': 'Юридическая информация',
            },
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='video_url',
            field=models.URLField(verbose_name='URL видео с YouTube'),
        ),
    ]
